local text = require("i18n-status.text")

describe("text", function()
  describe("trim", function()
    it("trims leading and trailing whitespace", function()
      assert.equals("hello", text.trim("  hello  "))
      assert.equals("hello", text.trim("hello  "))
      assert.equals("hello", text.trim("  hello"))
      assert.equals("hello", text.trim("hello"))
    end)
  end)

  describe("extract_placeholders", function()
    it("extracts brace placeholders", function()
      local placeholders = text.extract_placeholders("Hello {{name}}, your balance is {balance}")

      assert.is_true(placeholders.name)
      assert.is_true(placeholders.balance)
    end)

    it("returns an empty table when no placeholders exist", function()
      assert.are.same({}, text.extract_placeholders("Hello world"))
    end)
  end)

  describe("placeholder_equal", function()
    it("compares placeholder sets", function()
      assert.is_true(text.placeholder_equal({ name = true }, { name = true }))
      assert.is_false(text.placeholder_equal({ name = true }, { other = true }))
    end)
  end)

  describe("split_i18n_key", function()
    it("splits namespace and key path", function()
      local namespace, key_path = text.split_i18n_key("common:greeting.message")

      assert.are.equal("common", namespace)
      assert.are.equal("greeting.message", key_path)
    end)

    it("rejects invalid keys", function()
      local namespace1, key_path1 = text.split_i18n_key("common")
      local namespace2, key_path2 = text.split_i18n_key(":message")
      local namespace3, key_path3 = text.split_i18n_key(nil)

      assert.is_nil(namespace1)
      assert.is_nil(key_path1)
      assert.is_nil(namespace2)
      assert.is_nil(key_path2)
      assert.is_nil(namespace3)
      assert.is_nil(key_path3)
    end)
  end)
end)
